# Generated by Django 6.0.1 on 2026-01-26 18:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('pet_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(max_length=50)),
                ('external_id', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('species', models.CharField(choices=[('DOG', 'Dog'), ('CAT', 'Cat')], default='DOG', max_length=10)),
                ('age_group', models.CharField(blank=True, max_length=20, null=True)),
                ('size', models.CharField(blank=True, max_length=5, null=True)),
                ('sex', models.CharField(blank=True, max_length=20, null=True)),
                ('breed_primary', models.CharField(blank=True, max_length=255, null=True)),
                ('breed_secondary', models.CharField(blank=True, max_length=255, null=True)),
                ('is_mixed', models.BooleanField(default=False)),
                ('photos', models.JSONField(blank=True, default=list)),
                ('raw_description', models.TextField(blank=True, null=True)),
                ('ai_description', models.TextField(blank=True, null=True)),
                ('temperament_tags', models.JSONField(blank=True, default=list)),
                ('special_needs_flags', models.JSONField(blank=True, default=list)),
                ('listed_at', models.DateTimeField(blank=True, null=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AdopterProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_type', models.CharField(blank=True, max_length=50, null=True)),
                ('has_kids', models.BooleanField(default=False)),
                ('has_dogs', models.BooleanField(default=False)),
                ('has_cats', models.BooleanField(default=False)),
                ('activity_level', models.CharField(blank=True, max_length=20, null=True)),
                ('experience_level', models.CharField(blank=True, max_length=20, null=True)),
                ('preferences', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='adopter_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('organization_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(max_length=50)),
                ('source_org_id', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['is_active'], name='adoption_or_is_acti_2ba05e_idx')],
                'constraints': [models.UniqueConstraint(fields=('source', 'source_org_id'), name='uniq_org_source_provider_id')],
            },
        ),
        migrations.CreateModel(
            name='RiskClassification',
            fields=[
                ('pet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='risk', serialize=False, to='adoption.pet')),
                ('is_long_stay', models.BooleanField(default=False)),
                ('is_senior', models.BooleanField(default=False)),
                ('is_medical', models.BooleanField(default=False)),
                ('is_overlooked_breed_group', models.BooleanField(default=False)),
                ('recently_returned', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='VisibilityScore',
            fields=[
                ('pet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='visibility', serialize=False, to='adoption.pet')),
                ('base_score', models.FloatField(default=0.0)),
                ('boost_long_stay', models.FloatField(default=0.0)),
                ('boost_risk', models.FloatField(default=0.0)),
                ('boost_returned', models.FloatField(default=0.0)),
                ('penalty_high_adopt_prob', models.FloatField(default=0.0)),
                ('final_score', models.FloatField(default=0.0)),
                ('computed_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='pet',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pets', to='adoption.organization'),
        ),
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('interest_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interests', to=settings.AUTH_USER_MODEL)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interests', to='adoption.pet')),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('application_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='adoption.organization')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='adoption.pet')),
            ],
        ),
        migrations.AddIndex(
            model_name='pet',
            index=models.Index(fields=['status'], name='adoption_pe_status_fa4fef_idx'),
        ),
        migrations.AddIndex(
            model_name='pet',
            index=models.Index(fields=['species'], name='adoption_pe_species_2b8f8f_idx'),
        ),
        migrations.AddIndex(
            model_name='pet',
            index=models.Index(fields=['listed_at'], name='adoption_pe_listed__a9952c_idx'),
        ),
        migrations.AddConstraint(
            model_name='pet',
            constraint=models.UniqueConstraint(fields=('source', 'external_id'), name='uniq_pet_source_external_id'),
        ),
        migrations.AddIndex(
            model_name='interest',
            index=models.Index(fields=['created_at'], name='adoption_in_created_cd04f8_idx'),
        ),
        migrations.AddIndex(
            model_name='interest',
            index=models.Index(fields=['notification_status'], name='adoption_in_notific_9c2126_idx'),
        ),
        migrations.AddConstraint(
            model_name='interest',
            constraint=models.UniqueConstraint(fields=('user', 'pet'), name='uniq_interest_user_pet'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['created_at'], name='adoption_ap_created_0e86fe_idx'),
        ),
        migrations.AddConstraint(
            model_name='application',
            constraint=models.UniqueConstraint(fields=('user', 'pet'), name='uniq_application_user_pet'),
        ),
    ]
