# Generated by Django 6.0.1 on 2026-02-07 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoption', '0002_providersyncstate'),
    ]

    operations = [
        migrations.AddField(
            model_name='providersyncstate',
            name='lock_acquired_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='providersyncstate',
            name='lock_owner',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
