# Generated by Django 6.0.1 on 2026-02-10 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoption', '0003_providersyncstate_lock_acquired_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interest',
            name='notification_attempted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
