# Generated by Django 6.0.1 on 2026-02-11 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoption', '0004_interest_notification_attempted_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adopterprofile',
            name='activity_level',
            field=models.CharField(choices=[('LOW', 'Low'), ('MED', 'Med'), ('HIGH', 'High')], default='MED', max_length=10),
        ),
        migrations.AlterField(
            model_name='adopterprofile',
            name='experience_level',
            field=models.CharField(choices=[('NEW', 'New'), ('SOME', 'Some'), ('EXPERIENCED', 'Experienced')], default='SOME', max_length=15),
        ),
        migrations.AlterField(
            model_name='adopterprofile',
            name='home_type',
            field=models.CharField(choices=[('APARTMENT', 'Apartment'), ('HOUSE', 'House'), ('OTHER', 'Other')], default='OTHER', max_length=20),
        ),
    ]
