# Generated by Django 6.0.1 on 2026-02-12 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoption', '0005_alter_adopterprofile_activity_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adopterprofile',
            name='home_postal_code',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='organization',
            name='postal_code',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
