# Generated by Django 6.0.1 on 2026-02-13 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoption', '0006_adopterprofile_home_postal_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='apply_hint',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='pet',
            name='apply_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
