# Generated by Django 6.0.1 on 2026-02-13 17:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoption', '0007_pet_apply_hint_pet_apply_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='email_status',
            field=models.CharField(choices=[('SENT', 'Sent'), ('FAILED', 'Failed')], default='SENT', max_length=10),
        ),
        migrations.AlterField(
            model_name='application',
            name='pet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='adoption.pet'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['email_status'], name='adoption_ap_email_s_cafa83_idx'),
        ),
    ]
