# Generated by Django 6.0.1 on 2026-02-15 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoption', '0008_application_email_status_alter_application_pet_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='handoff_payload',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='application',
            name='profile_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
