# Generated by Django 6.0.1 on 2026-02-21 02:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoption', '0010_petseen'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PetImpression',
            fields=[
                ('impression_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('page_cursor_key', models.CharField(blank=True, default='', max_length=512)),
                ('page_limit', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impressions', to='adoption.pet')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pet_impressions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'created_at'], name='adoption_pe_user_id_472d57_idx'), models.Index(fields=['user', 'page_cursor_key'], name='adoption_pe_user_id_bca636_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'pet', 'page_cursor_key', 'page_limit'), name='uniq_pet_impression_user_pet_cursor_limit')],
            },
        ),
    ]
